### ISSUE TITLE
exception=ZeroDivisionError('division by zero')

### ISSUE THREAD

**Issue by iKap** [krakenrf/krakensdr_docs#11]
Hi !

I'm trying to bring up KrakenSDR with Zotac ZBox PI335 pico (ZBOX-PI335-GK-W3C) and DragonOS Linux installed on it.
After setting all up as described at 
https://github.com/krakenrf/krakensdr_docs/wiki/10.-VirtualBox,-Docker-Images-and-Install-Scripts
section "Install scripts / x86 64 Bit Systems"

after starting 
./kraken_doa_start.sh

service is up and I can access it through the web (192.168.1.175:8080) I see the GUI but when I trying to press anything (any button) on Configuration page - nothing happens, system do not starts at all and I see error in the Linux console of ZBox

```
Traceback for <Task finished name='Task-409' coro=<Pusher.dispatch() done, defined at /root/miniconda/envs/kraken/lib/python3.9/site-packages/quart/ctx.py:386> exception=ZeroDivisionError('division by zero')> (most recent call last):
ZeroDivisionError: division by zero
```
(full log in attached file)
[DivisionByZero.txt](https://github.com/krakenrf/krakensdr_docs/files/9627705/DivisionByZero.txt)

Same on the screenshot:

![div_by_zero](https://user-images.githubusercontent.com/2234562/191802385-fbd24cb2-ecb7-4363-99e9-28ec3eb6df8d.jpg)

Need to note that I've tried same on the Ubuntu 20.04.4 LTS
same under docker running on DragonOS

Going to try with Raspberry PI 4 model B 8G
I don't think it really related to the architectural properties of Intel N4100 (Gemini Lake)  (quad-core 1.1 GHz, up to 2.4 GHz)
Most likely related with some software mismatch.
Any practical ideas are welcome. 

Please help, I can't start the KrakenSDR

**Comment by krakenrf** [comment]
This error generally means that not all channels of the KrakenSDR started, or none started. 99% of the time it's the KrakenSDR power supply being insufficient. What power supply are you using with it?

**Comment by iKap** [comment]
Thanks for the reply.
I've checked my power (replaced power supply, cable) connected power meter to see the consumption - it show 5.2V, 0.88A max
(checked this power supply and
![photo_2022-09-25_14-21-45](https://user-images.githubusercontent.com/2234562/192143110-df7601cf-7e3d-427b-9042-f9e8a2904ca7.jpg)
 cable with smartphone - it gives quick charge good)

I see the device on the USB:

```
~$ lsusb -d:2838
Bus 001 Device 012: ID 0bda:2838 Realtek Semiconductor Corp. RTL2838 DVB-T
Bus 001 Device 009: ID 0bda:2838 Realtek Semiconductor Corp. RTL2838 DVB-T
Bus 001 Device 008: ID 0bda:2838 Realtek Semiconductor Corp. RTL2838 DVB-T
Bus 001 Device 007: ID 0bda:2838 Realtek Semiconductor Corp. RTL2838 DVB-T
Bus 001 Device 011: ID 0bda:2838 Realtek Semiconductor Corp. RTL2838 DVB-T
```

but using rtl_test I see unstable output:

```
zbox@zotac$ rtl_test -d0
Found 5 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 
  1:  , , SN: 
  2:  , , SN: 
  3:  , , SN: 1002
  4:  Realtek, , SN: 1003

Using device 0: Generic RTL2832U OEM
usb_claim_interface error -5
Failed to open rtlsdr device #0.
zbox@zotac$ rtl_test -d0
Found 5 device(s):
  0:  , RTL2838UHIDIR, SN: 1004
  1:  , , SN: 
  2:  , , SN: 
  3:  Realtek, RTL2838UHIDIR, SN: 
  4:  Realtek, RTL2838UHIDIR, SN: 1003

Using device 0: Generic RTL2832U OEM
usb_claim_interface error -5
Failed to open rtlsdr device #0.
zbox@zotac$ rtl_test -d0
Found 5 device(s):
  0:  Realtek, , SN: 1004
  1:  , , SN: 
  2:  , , SN: 
  3:  Realtek, , SN: 1002
  4:  , , SN: 

Using device 0: Generic RTL2832U OEM
usb_claim_interface error -5
Failed to open rtlsdr device #0.

zbox@zotac$ rtl_test -d0
Found 5 device(s):
  0:  , , SN: 
  1:  , , SN: 
  2:  , , SN: 
  3:  , RTL2838UHIDIR, SN: 
  4:  , RTL2838UHIDIR, SN: 1003

Using device 0: Generic RTL2832U OEM
usb_claim_interface error -5
Failed to open rtlsdr device #0.
```

Please suggest me how can I get more debug 
Probably I need to upgrade firmware on the KrakenSDR box?

**Comment by iKap** [comment]
After recompilling librtlsdr & install 
have a lot of errors on rtl_test
(log file attached)
[rtl_test_errors.log](https://github.com/krakenrf/krakensdr_docs/files/9640795/rtl_test_errors.log)

**Comment by krakenrf** [comment]
Okay so rtl_test show's some issue with the driver install, or USB connection.

Is there anything else preinstalled on that PC that could be accessing the RTL-SDR units on the KrakenSDR? The error from rtl_test indicates that something else has a hold of the tuner units. 

Can you check the DVB-T blacklist file at /etc/modprobe.d/blacklist-dvb_usb_rtl28xxu.conf, and make sure `blacklist dvb_usb_rtl28xxu` is written in it?

How long is your USB data cable? Try a shorter cable if you can. Also try connecting to a USB 3.0 port on that machine, or a different USB port.

There is no firmware to update. Power supply looks good.

**Comment by iKap** [comment]
Success !
It was a data cable. I replaced it with another short one and it starts.
I've also checked blacklist file and there are a lot of identical dvb_usb_rtl28xxu records. Will clean it up.
It works !!
Thanks a lot !
![KrakenSDR_GUI_RUN](https://user-images.githubusercontent.com/2234562/192245479-62954160-a21a-4b82-b685-8399745c3be5.png)
Thanks for the quick and effective support!
