### ISSUE TITLE
bearing lines and accuracy

### ISSUE THREAD

**Issue by cisrgistics** [krakenrf/krakensdr_docs#12]
Whether UCA or ULA the bearing lines generated while on the hunt dont appear on my screen like I have seen on the screenshots and youtube videos. I only see the red, blue and teal lines. Depending on other settings the odd ball shapes of detection from the antenna are red when the signal is inactive and black with sound when the signal is active. If I dont guess on the setting that dont have clear explanations and leave everything default, the noise floor takes over on changing environments and I never find anything legit.

What is the difference in entering the center frequency and gain, then updating versus the VFO frequency block at the bottom of the server screen? Why dont they default as equal until a more specific target is highlighted on the specrum screen. Why not reframe the center frequency box to that, plus full/half/quarter bandwidth selections, gain and target VFO or target freq. Even then the auto VFO mode defeats the point of writing in or selecting a freq in spectrum if it goes after the strongest freq in the spetrum.

Using RaioID dot net, I have struggled to find DMR signals at city halls and known locations. Kraken seems to find the signal everywhere but where it should be. In UCA it declared it in someones backyard. In ULA, three separate attempts, it declared it at an intersection under an overpass, two cities away and ten miles in the opposite direction. Three attempts with ULA and it never got close! Correct antenna spacing, quarter/half/full wavelength height antennas, kraken antennas.

There needs to be more screenshots depicting setting defaults and setting changes with data from actual signal hunts and photos of arrays setup on a vehicle in your "vehical axis" config, the zero degree 90 counterclockwise and zero degree 90 clockwise setups. I have done leading antenna at the front of the roof to last antenna near the trunck, and left side of the vehicle to right and right to left.

Trying use the spectrum display on anything other than a computer is impossible. The screen doesn't zoom on a pinch and the zoom buttons and other features are so tiny theyre impossible to use on a phone screen. 

The wiki for the software as bit of a blowoff attitude toward several of the features. Especially the "generally not required/generally not needed" comments. If it's not important why the effort to include it? Is there any correlation of dB and squelch on the spectrum and setting it to the power setting option from -200 to 0? If there is, why dont they sync up?

In some ways, using a DRT-1201B, AOR-5000 and AN/ULR-21 was easier and more transparent than learning this software AND getting results. Consistent results.

Last, can a RPi400 run two KrakenSDRs simultaneously for a 10 antenna array in either a T, Y, X, I, V or circular pattern?

**Comment by krakenrf** [comment]
Duplicate.
