### ISSUE TITLE
bearing lines and accuracy

### ISSUE THREAD

**Issue by cisrgistics** [krakenrf/krakensdr_docs#13]
Whether UCA or ULA the bearing lines generated while on the hunt don't appear on my screen like I have seen on the screenshots and YouTube videos. I only see the red, blue and teal lines. Depending on other settings the odd ball shapes of detection from the antenna are red when the signal is inactive and black with sound when the signal is active. If I don't guess on the setting that don't have clear explanations and leave everything default, the noise floor takes over on changing environments and I never find anything legit.

What is the difference in entering the center frequency and gain, then updating versus the VFO frequency block at the bottom of the server screen? Why don't they default as equal until a more specific target is highlighted on the spectrum screen. Why not reframe the center frequency box to that, plus full/half/quarter bandwidth selections, gain and target VFO or target freq. Even then the auto VFO mode defeats the point of writing in or selecting a freq in spectrum if it goes after the strongest freq in the spectrum.

Using RaioID dot net, I have struggled to find DMR signals at city halls and known locations. Kraken seems to find the signal everywhere but where it should be. In UCA it declared it in someone's backyard. In ULA, three separate attempts, it declared it at an intersection under an overpass, two cities away and ten miles in the opposite direction. Three attempts with ULA and it never got close! Correct antenna spacing, quarter/half/full wavelength height antennas, kraken antennas.

There needs to be more screenshots depicting setting defaults and setting changes with data from actual signal hunts and photos of arrays setup on a vehicle in your "vehical axis" config, the zero degree 90 counterclockwise and zero degree 90 clockwise setups. I have done leading antenna at the front of the roof to last antenna near the trunk, and left side of the vehicle to right and right to left.

Trying use the spectrum display on anything other than a computer is impossible. The screen doesn't zoom on a pinch and the zoom buttons and other features are so tiny they're impossible to use on a phone screen. 

The wiki for the software as bit of a blowoff attitude toward several of the features. Especially the "generally not required/generally not needed" comments. If it's not important why the effort to include it? Is there any correlation of dB and squelch on the spectrum and setting it to the power setting option from -200 to 0? If there is, why dont they sync up?

In some ways, using a DRT-1201B, AOR-5000 and AN/ULR-21 was easier and more transparent than learning this software AND getting results. Consistent results.

Last, can a RPi400 run two KrakenSDRs simultaneously for a 10-antenna array in either a T, Y, X, I, V or circular pattern? Do yall approve of the mixtile 3.0 sbc also on crowdsupply as adequate computing power?

**Comment by krakenrf** [comment]
Can you upload a screenshot of what your bearings look like on the App?

> What is the difference in entering the center frequency and gain, then updating versus the VFO frequency block at the bottom of the server screen?

The center frequency is what is actually tuned in the hardware. Every center frequency change results in a hardware operation, and a resync operation, which takes a few seconds. The VFO frequency is what you can tune instantly in software, as long as it's within the +/- 1.2 MHz of the center frequency.

> Why don't they default as equal until a more specific target is highlighted on the spectrum screen. Why not reframe the center frequency box to that, plus full/half/quarter bandwidth selections, gain and target VFO or target freq. Even then the auto VFO mode defeats the point of writing in or selecting a freq in spectrum if it goes after the strongest freq in the spectrum.

I'm not entirely sure what you mean here, can you clarify?

> I have struggled to find DMR signals at city halls and known locations

Please upload photos of your antenna and Kraken setup, and the settings you're using, and any log files from the Android app. If you want to keep the locations private email the logs to thekraken@krakenrf.com.

> Trying use the spectrum display on anything other than a computer is impossible. The screen doesn't zoom on a pinch and the zoom buttons and other features are so tiny they're impossible to use on a phone screen.

Yes the web based library for displaying the spectrum is a bit finnicky on touch devices. On those devices it's better to enter any VFO details via the config screen, and have some idea of what frequency you want to work with beforehand.

> The wiki for the software as bit of a blowoff attitude toward several of the features. Especially the "generally not required/generally not needed" comments. If it's not important why the effort to include it?

The Wiki is ever improving, if you have specific suggestions of queries about certain features let us know. If it's mentioned as 'generally not needed', then it's probably a feature for advanced users who already know what to do.

> Is there any correlation of dB and squelch on the spectrum and setting it to the power setting option from -200 to 0? If there is, why dont they sync up?

Are you referring to the Power setting on the Android App? This is just for filtering out low quality weak signals if desired. The values match with the spectrum display units.

I am having a guess that you are maybe dealing with intermittent signals? In this case you should be using the Squelch feature on the Kraken software, not the power filtering on the Android app.

> Last, can a RPi400 run two KrakenSDRs simultaneously for a 10-antenna array in either a T, Y, X, I, V or circular pattern? Do yall approve of the mixtile 3.0 sbc also on crowdsupply as adequate computing power?

A Pi400 wouldn't be able to run two KrakenSDRs. Apart from the CPU, the USB would probably be saturated on a single USB controller. The specs of the RK3588 look great, but we haven't tested it yet, so cannot confirm. Again, running two is really only possible if there are two independent USB controllers on a system which is unlikely to be found on an SBC. Also noting that two  wouldn't coherently work together, they would only work as independent coherent receivers.
