### ISSUE TITLE
Hash Codes for .ova System Image 

### ISSUE THREAD

**Issue by concinnitas** [krakenrf/krakensdr_docs#14]
I am wishing to verify the integrity of the .ova image I downloaded from the provided Google Drive link. I am having client issues with vbox getting the image to work and this would help my troubleshooting process.

**Comment by krakenrf** [comment]
Latest file hash. Note that the image had a minor update a few days ago.

Get-FileHash .\KrakenSDR_Ubuntu2204_071022.ova

SHA256          BB2C7022085CA055C99956B2F9AF18892EC21C395E19CA8746CB6534044DEC69

What issues are you having? Two people have reported difficultly downloading from the Google Drive, I'm not sure why. I tested multiple machines here and had others test overseas too, but can't replicate the download problem. Most people are downloading it fine though.

Going to find an alternative file host to upload it anyway, check the Wiki link again in a few hours.

**Comment by concinnitas** [comment]
Thanks, my .ova download was corrupted due to downloading on a mobile hotspot connection. I was able to re-download the file on a more reliable internet and verify the hash. VirtualBox was able to import the appliance without further problems.

For any experiencing difficulty with the preconfigured image, I received error message [Failed to import appliance S_ERROR_INVALID_ARG (0x80070057)]. This generic code could present for a variety of issues, including a corrupted appliance image.
