### ISSUE TITLE
Mismatch Headers for Log Data

### ISSUE THREAD

**Issue by Kaimbelic** [krakenrf/krakensdr_docs#15]
Hello,

I was working with the data coming from the kraken. From the appendix I was able to get data format pretty well.
There does seem to be a difference in the data that sampled and the format that is given.
Most notably is that at the 12th index of the log file should be `Heading Sensor Used` but instead there is a number in that location and the `Heading Sensor Used` is located in the 13th index.

Here is an example of the log where i quickly added the headers to double check.
![image](https://user-images.githubusercontent.com/38118010/197887561-17953052-b284-4d01-846b-46c1e677df97.png)

Just making sure that there is not an issue on my end.

Thanks

**Comment by krakenrf** [comment]
Thanks, I've edited the wiki now. The 12th index should actually have been the compass heading value. Which will only be non-zero if a compass sensor exists.
