### ISSUE TITLE
Mapbox Tile Ceiling Restrictions

### ISSUE THREAD

**Issue by concinnitas** [krakenrf/krakensdr_docs#16]
Is there any way to increase the tile ceiling above 6000? It is not enough for the area I would like to download offline.

**Comment by krakenrf** [comment]
Unfortunately not, this is a hard limit imposed by MapBox. You could instead try simply caching the area of interest at a lower resolution. Just scroll through the area of interest while zoomed out a little to cache those tiles. You won't get centimeter level mapping data, but hopefully it's enough.
