### ISSUE TITLE
rpi34_kerberossdr_image_18022020.zip pi4 image needs update

### ISSUE THREAD

**Issue by CarlFK** [krakenrf/krakensdr_docs#17]
rpi34_kerberossdr_image_18022020.zip (which came from a drive.google link, somewhere around here...

needs it's /boot files updated:
add to config.txt, hookup a serial contole:

```
carl@x1:~$ tio /dev/ttyUSB0 
[17:15:55.390] tio v2.5
[17:15:55.390] Press ctrl-t q to quit
[17:15:55.390] Connected

Read start4.elf bytes  2769540 hnd 0x0002e101 
Read fixup4.dat bytes     6167 hnd 0x00033c3d 
Firmware: cd3add54955f8fa065b414d8fc07c525e7ddffc8 Sep 24 2019 17:34:30
0x00d03115 0x00000000 0x00000000
start4.elf: is not compatible
This board requires newer software
Get the latest software from https://www.raspberrypi.org/downloads/
ERROR: 00000044
Retry SD 1
SD HOST: 250000000 CTL0: 0x00000000 BUS: 100000 Hz actual: 100000 HZ div: 2500 (1250) status: 0x1fff0000 delay: 1080
SD HOST: 250000000 CTL0: 0x00000f00 BUS: 100000 Hz actual: 100000 HZ div: 2500 (1250) status: 0x1fff0000 delay: 1080
OCR c0ff8000 [2]
CID: 001b534d454534533530e82755d8014b
CSD: 400e00325b59000775ff7f800a400000
SD: bus-width: 4 spec: 2 SCR: 0x02058483 0x00000000
SD HOST: 250000000 CTL0: 0x00000f04 BUS: 50000000 Hz actual: 41666666 HZ div: 6 (3) status: 0x1fff0000 delay: 2
MBR: 0x00002000,  524288 type: 0x0c
MBR: 0x00082000,14559232 type: 0x83
MBR: 0x00000000,       0 type: 0x00
MBR: 0x00000000,       0 type: 0x00
Trying partition: 0
lba: 8192 oem: 'mkfs.fat' volume: ' boot       '
rsc 32 fat-sectors 4033 c-count 516190 c-size 1 r-dir 2 r-sec 0
PM_RSTS: 0x00001000
Trying partition: 0
lba: 8192 oem: 'mkfs.fat' volume: ' boot       '
rsc 32 fat-sectors 4033 c-count 516190 c-size 1 r-dir 2 r-sec 0

Read config.txt bytes     1814 hnd 0x00033ce7 
Read start4.elf bytes  2769540 hnd 0x0002e101 
Read fixup4.dat bytes     6167 hnd 0x00033c3d 
Firmware: cd3add54955f8fa065b414d8fc07c525e7ddffc8 Sep 24 2019 17:34:30
```

**Comment by krakenrf** [comment]
Is this not just because you have an older batch of Pi4 and have never updated the firmware on it?

**Comment by cleverca22** [comment]
```
start4.elf: is not compatible
This board requires newer software
```
this error is reporting that start4.elf on the boot media is too old

you need to get the latest start4.elf + fixup4.dat from https://github.com/raspberrypi/firmware/tree/master/boot

**Comment by CarlFK** [comment]
"your start4.elf likely lacks support for 8gig of ram"
(I recall seeing some image does not work with 8gig pi, so maybe this fixes that too.)

git clone --depth 1 --filter=blob:none https://github.com/raspberrypi/firmware
(it's a big repo.  If someone can tell me how to only get the /boot/ dir, that would b

rsync -rtvP firmware/boot/ /media/carl/boot

carl@x1:~/temp/rpi/krak/boot$ tio /dev/ttyUSB0 
[11:31:38.543] tio v2.5
[11:31:38.543] Press ctrl-t q to quit
[11:31:38.543] Connected
Read start4.elf bytes  2250848 hnd 0x000516c5 
Read fixup4.dat bytes     5398 hnd 0x00042926 
Firmware: 658f02cc8edcb68a568273f05d2b6ceede181e15 Jan 18 2023 12:28:01
0x00d03115 0x00000000 0x00001fff
MEM GPU: 76 ARM: 948 TOTAL: 1024
Starting start4.elf @ 0xfec00200 partition 0
PCI reset

And it boots to the desktop now.

**Comment by cleverca22** [comment]
updating kernel.img can cause more issues, because then your /lib/modules is out of sync, and loadable modules stop working

thats why its recommended to only update the 2 files that are causing the issue

**Comment by krakenrf** [comment]
Ah right, this was my confusion, you are attempting to load a much older KerberosSDR image. Is there any reason that you need this image instead of the new software? The new software is also compatible with KerberosSDR hardware.

**Comment by CarlFK** [comment]
a few days ago I was clicking around trying to figure out what software to use, and it was the first thing I found.

I tried to find the page that linked to it, can't find it now.  All I can remember about it was the page had something like: "doesn't work on 8gig pi4, hopefully the raspios people fix this."

**Comment by krakenrf** [comment]
Are you running a KrakenSDR or KerberosSDR?

When we first started the Kerberos image Raspberry Pi OS had a bug that meant 8GB Pi's were not compatible unless you installed everything from scratch. Pi Foundation finally fixed that and the new KrakenSDR images don't have this issue.

**Comment by CarlFK** [comment]
issue title updated ;)

I wish I could tell you how I found
rpi34_kerberossdr_image_18022020.zip 

I now understand it is outdated, so all that is left is to find it and remove it so no one else makes the same mistake I did.
