### ISSUE TITLE
Wiki link to appendix broken

### ISSUE THREAD

**Issue by RadioAndrea** [krakenrf/krakensdr_docs#18]
The link in [Section 1, additional hardware required](https://github.com/krakenrf/krakensdr_docs/wiki/01.-Additional-Hardware-Required) to the list of tested devices in the appendix is broken now that the appendix has moved from being section 11 to section 12.

Solution: Update link from
`https://github.com/krakenrf/krakensdr_docs/wiki/11.-Appendix#tested-devices`
to
`https://github.com/krakenrf/krakensdr_docs/wiki/12.-Appendix#tested-devices`

**Comment by krakenrf** [comment]
Thanks, fixed.
