### ISSUE TITLE
The device is not available for armed forces of Ukraine

### ISSUE THREAD

**Issue by SrgntSmerch** [krakenrf/krakensdr_docs#2]
Hi gents! As you probably know, we have a war in our homeland- Ukraine. We are fighting russian murderers, who are killing and raping civilian people in our cities and villages every day for nearly half a year now. They are shelling our houses with cruise and ballistic missiles. They are stealing our wheat. So, what's the point? We need to somehow put our sky and lands on control. Especially we need to have some good toolset to monitor russian electronic warfare nodes, those are being used against our UAVs, navigation, etc. Looks like, that your Kraken is a kind of a game-changer device for us in a current situation. And we badly need a few just right now. We'd like to buy it, if it's possible. Can you please help? An enormous amount of civilian people will say "thank you for saving our lives".

**Comment by maksymx** [comment]
Thumbs up to support 👍🏻

**Comment by and3rson** [comment]
I second this. This device would truly be a game-changer for protecting worldwide democracy and the lives of innocent people who are being slaughtered right now.

**Comment by krakenrf** [comment]
I can't say much more here, but please email thekraken@krakenrf.com for more info and verification.
