### ISSUE TITLE
API for any language?

### ISSUE THREAD

**Issue by ertimas** [krakenrf/krakensdr_docs#20]
Hi team,
I know you've got the GRC block, but I would really like to programmatically control/read from the radio.  Is that available, or on the roadmap?

Thanks

**Comment by krakenrf** [comment]
Nothing like this is on the roadmap as it's already sort of implemented. If you have a look at the GRC block code you'll see how easy it is to make a web socket connection and receive data and control the radio through that. Any language that supports sockets should be able to make it work.

**Comment by ertimas** [comment]
Thank you for clarifying.  That works for me!
