### ISSUE TITLE
Broken Images for Orange Pi5 B

### ISSUE THREAD

**Issue by Hard7Rock** [krakenrf/krakensdr_docs#23]
images : 

- 18_june_2024
- 01_March_2024

when writed to sd card - OPi not booting
when tried to mount on PC - system not see any partitions

**Comment by krakenrf** [comment]
The OPI5 partitions can only be seen on a Linux system, this is the way it comes like directly from the official Orange Pi 5 images.

What OPI5B model are you using? The SDCard images are working fine on mine, but mine is the one with wireless. Perhaps there are minor differences which mean it won't boot on others.
