### ISSUE TITLE
VirtualBox Password

### ISSUE THREAD

**Issue by tayebzaidi** [krakenrf/krakensdr_docs#5]
I had been having difficulty compiling from scratch to run this on my desktop PC (can't get an RPi 4 for now) and decided to try the VirtualBox implementation.

Attempting to run the `./kraken_doa_start.sh` script asks for a password and after attempting some basic guesses I gave up and wasn't able to find any additional information in the documentation on what the password to the Ubuntu 22.04 Virtualbox machine is.

What is the password? And can this be added into the wiki? Thanks for all your work!

**Comment by krakenrf** [comment]
krakenrf/krakensdr

Sorry should definitely have that on the Wiki

**Comment by krakenrf** [comment]
BTW if you want open another issue for the install issues you're having. 

Have a look in the krakensdr_doa/ui.log and heimdall_daq_fw/Firmware/_logs folder for any clues that might help.
