### ISSUE TITLE
WIKI extension: What to do if Connection Status, Sample delay Sync and IQ Sync remain red?

### ISSUE THREAD

**Issue by Watchkido** [krakenrf/krakensdr_docs#7]
Please add the error to the wiki: What to do if Connection Status, Sample delay Sync and IQ Sync remain red?

**Comment by krakenrf** [comment]
Are you specifically encountering these issues? Please describe your full setup.

**Comment by Watchkido** [comment]
3 partial videos a 10 min 1. commissioning (Faulty audio track)
  https://youtu.be/bZPbvxHkzuA
https://youtu.be/nxCO9eYbw6s
https://youtu.be/gmSWxrlCtOI

**Comment by Kingpin348** [comment]
I am having the same problem. Using a Raspberry Pi 4b. I moved the USB cable to all USB ports and it never seems to connect to the software. I am using the latest DOA image feom 9/6/22 . See attached screenshot.
![Screenshot_20220908-141956_Chrome](https://user-images.githubusercontent.com/113153332/189253991-48c7af27-3ded-4b6d-82bc-9c3bfb66001d.jpg)

This is from the web interface screen. I've swapped ports and cables. I can't get the software to seemingly control the radio. Radio has power.

**Comment by galaris** [comment]
> I am having the same problem. Using a Raspberry Pi 4b. I moved the USB cable to all USB ports and it never seems to connect to the software. I am using the latest DOA image feom 9/6/22 . See attached screenshot. ![Screenshot_20220908-141956_Chrome](https://user-images.githubusercontent.com/113153332/189253991-48c7af27-3ded-4b6d-82bc-9c3bfb66001d.jpg)
> 
> This is from the web interface screen. I've swapped ports and cables. I can't get the software to seemingly control the radio. Radio has power.

I have the same screen. Initially everything is green, but then I change the frequency and click update, then it becomes like this. I suspect a power issue in my car, either the PI or the Kraken not receiving enough juice maybe. I will test it later.

**Comment by krakenrf** [comment]
> 3 partial videos a 10 min 1. commissioning (Faulty audio track) https://youtu.be/bZPbvxHkzuA https://youtu.be/nxCO9eYbw6s https://youtu.be/gmSWxrlCtOI

What power supply specs are you using with the Kraken? And did you have the Kraken plugged in and powered up when you booted the Pi?

From what I can see the Kraken SW is starting, but it cannot connect to the Krakens. Most likely that indicates the Kraken's power supply is insufficient. You need a good 2.4A+ power supply.

**Comment by krakenrf** [comment]
Remember you need a good 2.4A or better power supply for the Kraken otherwise the RTL-SDR tuners inside will be unable to start up. This is the most likely cause of it showing disconnected on the screen.

Second most likely issue is booting the Pi without the Kraken plugged in. The Kraken needs to be plugged in and powered before booting.

Third most likely could be a poor quality USB data cable.

**Comment by krakenrf** [comment]
> 3 partial videos a 10 min 1. commissioning (Faulty audio track) https://youtu.be/bZPbvxHkzuA https://youtu.be/nxCO9eYbw6s https://youtu.be/gmSWxrlCtOI

In video 3/3 it looks like you had it working, but I think you were confused with the start DOA button on the app? The start DOA button is the thin diagonal arrow, second from the bottom.

The start turn by turn navigation button is the thick north facing arrow and that's the one you were pressing.

**Comment by Watchkido** [comment]
Ok,thanks. I can start with that. But: What is a "GOOD" power supply or a "GOOD" cable?
Do you have a brand, an Amazon product or other parameters that describe "GOOD" in more detail. I have "the best", "better","super", "good" and "2.4A" written all over it.

**Comment by krakenrf** [comment]
> Ok,thanks. I can start with that. But: What is a "GOOD" power supply or a "GOOD" cable? Do you have a brand, an Amazon product or other parameters that describe "GOOD" in more detail. I have "the best", "better","super", "good" and "2.4A" written all over it.

For a good power supply, it should advertise a current handling capacity of at least 2.4A. These days most should advertise 3A which would be even safer. 

But a problem is, even if they advertise 3A, some on Amazon are fake and can't actually provide that much current. In our test setups we normally use an official Raspberry Pi 4 USB-C power supply each for the Pi 4 and Kraken. In a vehicle I use a 2 port 12V USB adapter which has 3A PER PORT capability. 

Unfortunately that is the problem with cables and supplies on Amazon. Despite the advertising it can sometimes be trial and error and browsing the reviews to find one that actually meets the advertising. I purchased my cables and 12V adapter from a local computer store chain. I chose the thickest 1.5m cables and a 12V adapter that specifically stated 3A per port. The brands in my country aren't on Amazon.

In the future we're going to source some confirmed quality supplies and accessories like 12V cigarette adapters for our store. But those things are taking some time as we need to be sure they all meet the power supply and EMC regulations for each country.

**Comment by turbo2ltr** [comment]
I have to say I'm having the same issue.  It works when you first boot.  Works, as in I see it going through it's process with the noise on, it finally everything turns green with the latency and update rate being updated regularly. But as soon as you update anything like, say, change the frequency, and press "Update receiver parameters", it looks like it worked, but the latency stops updating. If you go to the spectrum, it's not doing anything (solid orange waterfall, and no waveform). DOA screen is a straight diagonal line.
If you go back to the config page, now everything is red.  Update the receive params and it turns green again, but same deal.

I've tried 3 different power supplies, including one that I have load tested to 3A and one that I have load tested to 8A. I've tried several different cables including thick ones and short ones.  I can't seem to get it to do anything different.

Update: So everything does seem to work as long as you don't hit "update receive params".  If you boot it and don't hit that, and go to the spectrum, it does show up and appears to work.   So I updated the freq, saved the config so the next time it booted, it came up with the frequency I  wanted and I was able to get some proper output from the app.

Also, when it's working, and I shutdown the Pi, it shuts down almost immediately.  If I "crash" it by clicking the Update Receiver Params, the shutdown shows a stuck process that it has to force shutdown after a 90 second timeout.

Hopefully these are some useful clues.

**Comment by krakenrf** [comment]
Can you please try a few things?

1) First download the latest image file and see if anything recent fixes things
2) Update your Pi4's EEPROM https://www.yoctopuce.com/EN/article/how-to-fix-raspberry-pi-4-usb-stack
3) Check krakensdr_doa/krakensdr_doa/ui.log, and the logs in krakensdr_doa/heimdall_daq_fw/Firmware/_logs for any error messages

**Comment by turbo2ltr** [comment]
I just did the first thing in the list and that seems to have addressed the issue.  When I change frequencies, there is a calibration and then it goes all green and the spectrum and DOA work.

Thanks!
