### ISSUE TITLE
Example 3 - Cross Correlation Sample and Phase Coherent Check - Exception Failed to put IQ Samples into the Queue

### ISSUE THREAD

**Issue by anthfuller** [krakenrf/krakensdr_docs#9]
Receiving a numerous amount of these when running the example below: 
**Example 3 - Cross Correlation Sample and Phase Coherent Check**

Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Sending control message
Control interface communication finished
Reconfiguration succesfully finished
Sending control message
Control interface communication finished
Reconfiguration succesfully finished
Sending control message
Control interface communication finished
Reconfiguration succesfully finished
/usr/local/lib/python3.10/dist-packages/gnuradio/krakensdr/krakensdr_correlator.py:46: RuntimeWarning: divide by zero encountered in log10
  x_corr_plot = 10*np.log10(np.abs(x_corr))
Failed to put IQ Samples into the Queue
Exception:

**Comment by anthfuller** [comment]
I meant to mention, this isn't running on a Pi4, but a x86 machine with Ubuntu 22.04 running. I also used the automatic script, had trouble with the manual. This is also a fresh OS install.

**Comment by anthfuller** [comment]
This is probably root cause of the issues: 

"The problem is that taking the log10 of anything <= 0 is undefined mathematically, and Python is (quite rightly)
  raising an exception.

I guess the KrakenSDR correlator block calls log10 underneath, and it doesn't take care to avoid the zone
  of undefinedness.

When I've encountered this problem, I just add a *tiny* amount to my samples to make sure they're never
  <= 0.  This usually only happens at startup, when buffers may have been zero-padded in the beginning."

Is there a fix or workaround for this or should I look into the sample size?

**Comment by anthfuller** [comment]
Ok, after close to a years wait, where is the support for this please? Three days have passed by? I need some assistance on this issue please. I would have purchased a USRP-B210, Ettus & NI support from their ratings is phenominal! I've been trying to fix this issue with this code for three days and at least you could acknowledge your working on this?

**Comment by krakenrf** [comment]
Duplicate issue
